name: CI

on: [push]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    container:
      image: baijunyao/php:8.0-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
      - name: PHP CS Fixer
        run: |
          ./vendor/bin/php-cs-fixer fix --verbose --show-progress=dots --dry-run --diff

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    container:
      image: baijunyao/php:8.0-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
      - name: PHPStan
        run: |
          ./vendor/bin/phpstan analyse --ansi

  markdown-lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1
  php_7_4_mysql_5_6:
    name: PHP7.4+MySQL5.6
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: laravel_bjyblog
          MYSQL_DATABASE: laravel_bjyblog
    container:
      image: baijunyao/php:7.4-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
          php artisan key:generate
          php artisan passport:keys
          php artisan migrate
          php artisan db:seed
          php artisan storage:link --relative
      - name: Test
        run: |
          ./vendor/bin/phpunit

  php_7_4_mysql_5_7:
    name: PHP7.4+MySQL5.7
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: laravel_bjyblog
          MYSQL_DATABASE: laravel_bjyblog
    container:
      image: baijunyao/php:7.4-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
          php artisan key:generate
          php artisan passport:keys
          php artisan migrate
          php artisan db:seed
          php artisan storage:link --relative
      - name: Test
        run: |
          ./vendor/bin/phpunit

  php_7_4_mysql_8_0:
    name: PHP7.4+MySQL8.0
    runs-on: ubuntu-latest
    services:
      mysql:
        image: baijunyao/mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: laravel_bjyblog
          MYSQL_DATABASE: laravel_bjyblog
    container:
      image: baijunyao/php:7.4-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
          php artisan key:generate
          php artisan passport:keys
          php artisan migrate
          php artisan db:seed
          php artisan storage:link --relative
      - name: Test
        run: |
          ./vendor/bin/phpunit

  php_8_0_mysql_5_6:
    name: PHP8.0+MySQL5.6
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: laravel_bjyblog
          MYSQL_DATABASE: laravel_bjyblog
    container:
      image: baijunyao/php:8.0-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
          php artisan key:generate
          php artisan passport:keys
          php artisan migrate
          php artisan db:seed
          php artisan storage:link --relative
      - name: Test
        run: |
          ./vendor/bin/phpunit

  php_8_0_mysql_5_7:
    name: PHP8.0+MySQL5.7
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: laravel_bjyblog
          MYSQL_DATABASE: laravel_bjyblog
    container:
      image: baijunyao/php:8.0-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
          php artisan key:generate
          php artisan passport:keys
          php artisan migrate
          php artisan db:seed
          php artisan storage:link --relative
      - name: Test
        run: |
          ./vendor/bin/phpunit

  php_8_0_mysql_8_0:
    name: PHP8.0+MySQL8.0
    runs-on: ubuntu-latest
    services:
      mysql:
        image: baijunyao/mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: laravel_bjyblog
          MYSQL_DATABASE: laravel_bjyblog
    container:
      image: baijunyao/php:8.0-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
          php artisan key:generate
          php artisan passport:keys
          php artisan migrate
          php artisan db:seed
          php artisan storage:link --relative
      - name: Test
        run: |
          ./vendor/bin/phpunit

  notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    needs: [phpcs, phpstan, php_7_4_mysql_5_6, php_7_4_mysql_5_7, php_7_4_mysql_8_0, php_8_0_mysql_5_6, php_8_0_mysql_5_7, php_8_0_mysql_8_0,]
    if: always()
    steps:
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v3.0.0
        if: always()
        with:
          slack_channel_id: CEWJP77BP
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
